// File: gui/lib/chunkingService.ts

// This service module is dedicated to handling the chunking and encryption/decryption of large files.
// It will be called by Feature 6 (for encryption) and Feature 7 (for decryption).

// Defines the structure of the object returned by the encryption function
export interface EncryptedLargeFilePayload {
  isChunked: true;
  originalFileName: string;
  chunks: { iv: Uint8Array; data: Uint8Array }[];
}

// Defines the structure of the object required by the decryption function
export interface DecryptLargeFilePayload {
  isChunked: true;
  originalFileName: string;
  chunks: { iv: Uint8Array; data: Uint8Array }[];
}


/**
 * Encrypts a large file by splitting it into chunks using a pre-generated session key.
 * This is the core of Feature 12.
 * @param {File} largeFile - The large file to be encrypted.
 * @param {CryptoKey} sessionKey - The AES-GCM session key, pre-generated by the caller (Feature 6).
 * @returns {Promise<EncryptedLargeFilePayload>} An object containing the encrypted chunks.
 */
export async function encryptLargeFile(largeFile: File, sessionKey: CryptoKey): Promise<EncryptedLargeFilePayload> {
  const CHUNK_SIZE = 1 * 1024 * 1024; // 1MB
  console.log(`Starting chunking and encryption for: "${largeFile.name}"`);

  // The session key is now provided, so we no longer generate it here.
  
  const encryptedChunks: { iv: Uint8Array; data: Uint8Array }[] = [];
  let chunkIndex = 0;

  console.log(`Splitting into ${Math.ceil(largeFile.size / CHUNK_SIZE)} chunks...`);
  for (let start = 0; start < largeFile.size; start += CHUNK_SIZE) {
    console.log(`Encrypting chunk #${chunkIndex + 1}...`);
    const chunk = largeFile.slice(start, start + CHUNK_SIZE);
    const chunkBuffer = await chunk.arrayBuffer();
    const iv = window.crypto.getRandomValues(new Uint8Array(12));

    const encryptedChunk = await window.crypto.subtle.encrypt(
      { name: "AES-GCM", iv: iv },
      sessionKey, // Using the provided key
      chunkBuffer
    );

    encryptedChunks.push({
      iv: iv,
      data: new Uint8Array(encryptedChunk),
    });
    chunkIndex++;
  }

  console.log("Large file encryption completed successfully.");
  
  // The returned object no longer contains the sessionKey
  return {
    isChunked: true,
    originalFileName: largeFile.name,
    chunks: encryptedChunks,
  };
}

/**
 * Decrypts a file that was encrypted in chunks.
 * This function will be called by Feature 7.
 * @param {DecryptLargeFilePayload} encryptedFileObject - The object containing the encrypted chunks.
 * @param {CryptoKey} sessionKey - The AES-GCM session key used for decryption.
 * @returns {Promise<Blob>} A Blob containing the decrypted data of the original file.
 */
export async function decryptChunkedFile(encryptedFileObject: DecryptLargeFilePayload, sessionKey: CryptoKey): Promise<Blob> {
  // This function does not need any changes.
  console.log(`Starting decryption for chunked file: "${encryptedFileObject.originalFileName}"...`);
  const decryptedChunks: Uint8Array[] = [];
  for (const [index, chunk] of encryptedFileObject.chunks.entries()) {
    console.log(`Decrypting chunk #${index + 1}...`);
    try {
      const decryptedChunk = await window.crypto.subtle.decrypt(
        { name: "AES-GCM", iv: chunk.iv },
        sessionKey,
        chunk.data
      );
      decryptedChunks.push(new Uint8Array(decryptedChunk));
    } catch (err) {
      console.error(`Failed to decrypt chunk #${index + 1}.`, err);
      throw new Error("Decryption failed. The file may be corrupt or the key is incorrect.");
    }
  }
  const fileBlob = new Blob(decryptedChunks, { type: 'application/octet-stream' });
  console.log("Chunked file decryption completed successfully.");
  return fileBlob;
}

/**
 * Helper function to calculate SHA-256 hash of a file for verification.
 * @param {File | Blob} file - The file or blob to hash.
 * @returns {Promise<string>} The hex string of the hash.
 */
export async function calculateFileHash(file: File | Blob): Promise<string> {
  const buffer = await file.arrayBuffer();
  const hashBuffer = await window.crypto.subtle.digest('SHA-256', buffer);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}